#!/bin/sh -e

interface="$1"
action="$2"
arptype="$3"

LOGGER="/usr/bin/logger -t iflinkd"

if test "x$arptype" != "xether"; then
	$LOGGER "$interface: unsupported ARP type: $arptype"
	exit 0
fi

# configure interface manualy if required
if test -s /etc/network/if-$interface; then
	if test "x$action" == "xlink"; then
		$LOGGER "$interface: found manual config"
		/bin/sh /etc/network/if-$interface $action
	else
		$LOGGER "$interface: removing address"
		/bin/ip addr flush dev $interface
		/bin/ip route flush dev $interface
	fi
	exit 0
fi

case $action in
	link)
		$LOGGER "$interface: starting dhcpcd"
		/usr/sbin/dhcpcd --quiet --hostname --noipv4ll --timeout 0 $interface &
		;;

	up | down)
		$LOGGER "$interface: stopping dhcpcd"
		/usr/sbin/dhcpcd --quiet --exit $interface
		;;

	*)
		$LOGGER "$interface: unsupported action: $action"
		;;
esac
