PACKAGE = medatom
VERSION = 0.0.0

dirs = \
	/bin \
	/dev \
	/etc \
	/etc/default \
	/etc/init.d \
	/etc/pango \
	/etc/network \
	/etc/network/if-down.d \
	/etc/network/if-post-down.d \
	/etc/network/if-pre-up.d \
	/etc/network/if-up.d \
	/etc/rcS.d \
	/etc/X11 \
	/etc/X11/xorg.conf.d \
	/media \
	/media/disk \
	/proc \
	/root \
	/sbin \
	/sys \
	/tmp \
	/usr \
	/usr/lib \
	/usr/lib/gdk-pixbuf-2.0 \
	/usr/lib/gdk-pixbuf-2.0/2.10.0 \
	/var \
	/var/run

scripts = \
	/etc/init.d/alsa \
	/etc/init.d/dbus \
	/etc/init.d/gconf \
	/etc/init.d/gdk-pixbuf \
	/etc/init.d/hal \
	/etc/init.d/modules \
	/etc/init.d/motd \
	/etc/init.d/networking \
	/etc/init.d/pango \
	/etc/init.d/rcS \
	/etc/init.d/syslogd \
	/usr/share/udhcpc/default.script

files = \
	/etc/asound.state \
	/etc/default/rcS \
	/etc/fstab \
	/etc/group \
	/etc/hostname \
	/etc/hosts \
	/etc/inittab \
	/etc/issue \
	/etc/modules \
	/etc/motd.tail \
	/etc/network/interfaces \
	/etc/passwd \
	/etc/profile \
	/etc/shadow \
	/etc/sysctl.conf \
	/etc/X11/xorg.conf.d/input.conf \
	/lib/lsb/init-functions \
	/root/.xinitrc

links = \
	/bin/sh \
	/etc/motd \
	/etc/pango/pango.modules \
	/etc/rcS.d/05-syslogd \
	/etc/rcS.d/10-modules \
	/etc/rcS.d/11-networking \
	/etc/rcS.d/20-alsa \
	/etc/rcS.d/50-dbus \
	/etc/rcS.d/51-hal \
	/etc/rcS.d/52-motd \
	/etc/rcS.d/53-gdk-pixbuf \
	/etc/rcS.d/54-pango \
	/etc/resolv.conf \
	/init \
	/sbin/getty \
	/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache

include platforms/common.mk
