PACKAGE = medatom
VERSION = 0.0.0

dirs = \
	/dev \
	/etc \
	/etc/default \
	/etc/init.d \
	/etc/network \
	/etc/network/if-down.d \
	/etc/network/if-post-down.d \
	/etc/network/if-pre-up.d \
	/etc/network/if-up.d \
	/etc/rcS.d \
	/etc/X11 \
	/etc/X11/xorg.conf.d \
	/media \
	/media/disk \
	/proc \
	/root \
	/sys \
	/tmp \
	/var \
	/var/run

scripts = \
	/etc/init.d/dbus \
	/etc/init.d/hal \
	/etc/init.d/modules \
	/etc/init.d/rcS \
	/etc/init.d/syslogd \
	/usr/share/udhcpc/default.script

files = \
	/etc/asound.state \
	/etc/default/rcS \
	/etc/fstab \
	/etc/group \
	/etc/hostname \
	/etc/hosts \
	/etc/inittab \
	/etc/issue \
	/etc/modules \
	/etc/motd.tail \
	/etc/network/interfaces \
	/etc/passwd \
	/etc/profile \
	/etc/shadow \
	/etc/sysctl.conf \
	/etc/X11/xorg.conf.d/input.conf \
	/lib/lsb/init-functions

links = \
	/etc/motd \
	/etc/rcS.d/05-syslogd \
	/etc/rcS.d/10-modules \
	/etc/rcS.d/50-dbus \
	/etc/rcS.d/51-hal \
	/etc/resolv.conf \
	/init

include platforms/common.mk
