#!/bin/sh -e

wait_for_partition()
{
	echo -n "waiting for partition $1 ..."
	while ! test -b "$1"; do
		echo -n .
		sleep 1
	done
	echo " done"
}

format_partition()
{
	echo -n "formatting $1 with $2 (label:$3) ... "
	/sbin/mkfs -t $2 -L $3 $1 > /dev/null 2>&1
	if test "x$?" = "x0"; then
		echo "done"
	else
		echo "failed"
	fi
}

if [ "x$1" = "x" ]; then
	echo "usage: $0 device"
	exit 1
fi

device="$1"

/sbin/sfdisk "$device" <<EOF
,512M,L,*
,128M,L
,,L
EOF

for directory in /usr/lib/syslinux /usr/share/syslinux; do
    if test -f "$directory/mbr.bin"; then
	cat "$directory/mbr.bin" > ${device}
	mbr_installed=yes
    fi
done

if test "x$mbr_installed" != "xyes"; then
    echo "MBR not found, try installing syslinux"
    exit 1
fi

wait_for_partition ${device}1
format_partition ${device}1 ext4 boot
wait_for_partition ${device}2
format_partition ${device}2 ext4 persist
wait_for_partition ${device}3
format_partition ${device}3 ext4 data

sleep 1

mount ${device}1 /media
extlinux --install /media
cat > /media/extlinux.conf << EOF
DEFAULT linux
LABEL linux
	KERNEL vmlinuz
	INITRD initrd.gz
	APPEND root=LABEL=boot:/rootfs.img drm_kms_helper.edid_firmware=edid/chimei-1366-768.bin
EOF
chown root:root /media/extlinux.conf
umount /media
