#!/bin/sh -e

wait_for_partition()
{
	echo -n "waiting for partition $1 ..."
	while ! test -b "$1"; do
		echo -n .
		sleep 1
	done
	echo " done"
}

format_partition()
{
	echo -n "formatting $1 with $2 (label:$3) ... "
	/sbin/mkfs -t $2 -L $3 $1 > /dev/null 2>&1
	if test "x$?" = "x0"; then
		echo "done"
	else
		echo "failed"
	fi
}

if [ "x$1" = "x" -o "x$2" = "x" ]; then
	echo "usage: $0 device source"
	exit 1
fi

device="$1"
source="$2"
mp="/media"

/sbin/sfdisk -uM "$device" <<EOF
,,L,*
EOF

if test -r /usr/lib/syslinux/mbr.bin ; then
	cat /usr/lib/syslinux/mbr.bin > ${device}
elif test -r /usr/share/syslinux/mbr.bin ; then
	cat /usr/share/syslinux/mbr.bin > ${device}
else
	echo "mbr.bin not found"
	exit 1
fi
wait_for_partition ${device}1
format_partition ${device}1 ext4 install

mount ${device}1 "$mp"
extlinux --install "$mp"
cat > "$mp/extlinux.conf" << EOF
DEFAULT linux
LABEL linux
	KERNEL vmlinuz
	INITRD initrd.gz
	APPEND quiet
EOF
chown root:root "$mp/extlinux.conf"
cp "$source/vmlinuz" "$mp/vmlinuz"
cp "$source/initrd.gz" "$mp/initrd.gz"
cp "$source/install.tar" "$mp/install.tar"
umount "$mp"
