#!/bin/sh -e

wait_for_partition()
{
	echo -n "waiting for partition $1 ..."
	while ! test -b "$1"; do
		echo -n .
		sleep 1
	done
	echo " done"
}

format_partition()
{
	echo -n "formatting $1 with $2 (label:$3) ... "
	/sbin/mkfs -t $2 -L $3 $1 > /dev/null 2>&1
	if test "x$?" = "x0"; then
		echo "done"
	else
		echo "failed"
	fi
}

if [ "x$1" = "x" -o "x$2" = "x" ]; then
	echo "usage: $0 device source"
	exit 1
fi

device="$1"
source="$2"
mp="/media"

/sbin/sfdisk "$device" <<EOF
,,L,*
EOF

for directory in /usr/lib/syslinux /usr/share/syslinux; do
	if test -f "$directory/mbr.bin"; then
		cat "$directory/mbr.bin" > ${device}
		mbr_installed=yes
	fi
done

if test "x$mbr_installed" != "xyes"; then
	echo "MBR not found, try installing syslinux"
	exit 1
fi

sync
wait_for_partition ${device}1
format_partition ${device}1 ext4 install

files="$source/extlinux.conf $source/vmlinuz $source/initrd.gz"
files="$files $source/install.tar"

test -f "$source/linux.c32" && files="$files $source/linux.c32"
test -f "$source/libcom32.c32" && files="$files $source/libcom32.c32"
test -f "$source/fdt.dtb" && files="$files $source/fdt.dtb"

mount ${device}1 "$mp"
extlinux --install "$mp"
cp -v $files "$mp"
umount "$mp"
