#!/bin/sh -e

interface="$1"
action="$2"
arptype="$3"

if test "x$arptype" != "xether"; then
	echo "$0: unsupported ARP type: $arptype"
	exit 0
fi

case $action in
	link)
		dhcpcd --quiet --hostname --noipv4ll --timeout 0 $interface
		;;

	down)
		dhcpcd --quiet --exit $interface || true
		;;

	*)
		;;
esac
