#!/bin/sh -e

interface="$1"
action="$2"

case $action in
	up)
		/bin/systemctl start ddip-announce@$interface.service
		;;

	down)
		/bin/systemctl stop ddip-announce@$interface.service
		;;

	*)
		;;
esac
