#!/bin/sh -e

interface="$1"
action="$2"

case $action in
	link)
		if /bin/systemctl is-active lldpd.service; then
			/bin/systemctl restart lldpd.service
		else
			/bin/systemctl start lldpd.service
		fi
		;;

	up | down)
		/bin/systemctl stop lldpd.service
		;;

	*)
		;;
esac
