#!/bin/sh -e

interface="$1"
action="$2"
arptype="$3"

if test "x$interface" = "xsl0"; then
	case $action in
		up | down)
			route del 169.254.1.2 dev $interface
			ifconfig $interface 0.0.0.0
			;;

		link)
			ifconfig $interface 169.254.1.1
			route add 169.254.1.2 dev $interface
			;;

		*)
			;;
	esac
fi
