#!/bin/sh -e

interface="$1"
action="$2"

case $action in
	link)
		/usr/sbin/dhcpcd --quiet --hostname --noipv4ll --timeout 0 $interface
		;;

	up | down)
		/usr/sbin/dhcpcd --quiet --exit $interface
		;;

	*)
		;;
esac
