#!/bin/sh -e

BASE='x'

find_gpiochip()
{
	for f in /sys/class/gpio/gpiochip*; do
		LABEL=$(cat "$f/label")
		if [ "$LABEL" = "$1" ]; then
			BASE=$(cat "$f/base")
			return 0
		fi
	done
	return 1
}

# retry with old-style naming
find_gpiochip "gpio-ad64p" || find_gpiochip "0000:05:00.0"

[ "$BASE" = "x" ] && { echo "Error: gpio chip not found."; exit 1; }

echo $((BASE+15)) > /sys/class/gpio/export
echo high > /sys/class/gpio/gpio$((BASE+15))/direction
