#!/bin/sh -e

function find_gpiochip
{
	for f in /sys/class/gpio/gpiochip*; do
		LABEL=`cat $f/label`
		if [ "$LABEL" = "$1" ]; then
			cat $f/base
			return 0
		fi
	done
	return 1
}

BASE=$(find_gpiochip "0000:05:00.0")
if [ $BASE = "" ]; then
	echo "Error: gpio chip not found."
	exit 1
fi

echo $(($BASE+15)) > /sys/class/gpio/export
echo high > /sys/class/gpio/gpio$(($BASE+15))/direction
