#!/bin/sh -e

interface="$1"
action="$2"
arptype="$3"

case $action in
	link)
		dhcpcd --quiet --hostname --noipv4ll --timeout 0 $interface
		;;

	up | down)
		dhcpcd --quiet --exit $interface
		;;

	*)
		;;
esac
