#!/bin/sh -e

PLATFORM="`cd ${0%/*}; pwd`"
TEGRA2_DIR="`cd $PLATFORM/../../../..; pwd`/tools/nvidia/tegra2"
FASTBOOT="$TEGRA2_DIR/fastboot.bin"

if test "x$1" = "x"; then
	display_type="hdmi"
else
	display_type="$1"
fi

case "$display_type" in
	hdmi)
		ODM="0x2b2d8011"
		;;

	lvds)
		ODM="0x2b0d8011"
		;;

	*)
		echo "Invalid display type, must be one of: hdmi, lvds."
		exit 1
		;;
esac

"$TEGRA2_DIR/nvflash" \
	--bct "$PLATFORM/tec.bct" --setbct \
	--configfile "$PLATFORM/tec.cfg" \
	--bl "$FASTBOOT" \
	--odmdata "$ODM" \
	--create --go
