#!/bin/sh

. /lib/lsb/init-functions

MODULE=ethoc
IFACE=eth0

usage() {
	echo "usage: $1 {start|stop}"
}

case $1 in
	start)
		log_action_begin_msg "Starting networking"
		/sbin/modprobe $MODULE
		/sbin/ifup eth0
		log_action_end_msg $?
		;;

	stop)
		log_action_begin_msg "Stopping networking"
		/sbin/ifdown eth0
		/sbin/modprobe -r $MODULE
		log_action_end_msg $?
		;;

	*)
		usage $0
		exit 1
		;;
esac
