#!/bin/sh

echo -n "Creating /tmp filesystem ... "
mount -t tmpfs none /tmp
echo "done"

echo -n "Creating /var filesystem ... "
mount -t tmpfs none /var
mkdir /var/cache
mkdir /var/cache/hald
mkdir /var/lib
mkdir /var/lib/xkb
mkdir /var/log
mkdir /var/run
mkdir /var/run/dbus
mkdir /var/run/hald
mkdir /var/run/hald/hald-local
mkdir /var/run/hald/hald-runner
echo "done"

echo -n "Configuring kernel parameters ... "
sysctl -p > /dev/null
echo "done"

echo -n "Populating /dev filesystem ... "
udevd --daemon
udevadm trigger
echo "done"

echo -n "Creating /dev/pts filesystem ... "
mkdir /dev/pts
mount -t devpts devpts /dev/pts
echo "done"

echo -n "Setting hostname ... "
hostname=`cat /etc/hostname`
hostname -F /etc/hostname
echo "$hostname"

echo -n "Unblanking /dev/tty0 ... "
echo -ne "\033[9;0]" > /dev/tty0
echo "done"

/bin/run-parts -a start /etc/rcS.d
