#!/bin/sh -e

persist="$1"
serial=`adak-mac -i eth0 serial`
suffix=""
if test $(cat /proc/cpuinfo | grep -c processor) -gt 2; then
	suffix="ng-"
fi
if test -z $serial; then
	serial="XXXXX"
fi
name="plutux-$suffix$serial"

. /lib/lsb/init-functions

# check if update is needed
if test -e "$persist/etc/hostname" ; then
	if test $name == `cat $persist/etc/hostname` ; then
		exit 0
	fi
fi

# check if filesystem is writable
log_action_begin_msg "Remounting persistent filesystem read-write"
mount -o remount,rw "$persist"
log_action_end_msg $?

# update hostname
echo $name > "$persist/etc/hostname"

# make sure filesystem is protected
log_action_begin_msg "Remounting persistent filesystem read-only"
mount -o remount,ro "$persist"
log_action_end_msg $?
