#!/bin/sh -e

interface="$1"
action="$2"
arptype="$3"

if test "x$arptype" != "xether"; then
	echo "unsupported ARP type: $arptype"
	exit 0
fi

# configure interface manualy if required
if test -s /etc/network/if-$interface; then
	if test "x$action" == "xlink"; then
		/usr/bin/logger -t dhcp "found manual config for $interface"
		/bin/sh /etc/network/if-$interface $action
	fi
	exit 0
fi

case $action in
	link)
		/usr/sbin/dhcpcd --quiet --hostname --noipv4ll --timeout 0 $interface &
		;;

	up | down)
		/usr/sbin/dhcpcd --quiet --exit $interface
		;;

	*)
		;;
esac
