#!/bin/sh -e

interface="$1"
action="$2"
arptype="$3"

if test "x$arptype" != "xether"; then
	echo "unsupported ARP type: $arptype"
	exit 0
fi

case $action in
	link)
		/usr/sbin/dhcpcd --quiet --hostname --noipv4ll --timeout 0 $interface
		;;

	up | down)
		/usr/sbin/dhcpcd --quiet --exit $interface
		;;

	*)
		;;
esac
