#!/bin/sh

. /lib/lsb/init-functions

ALSACTL=/usr/sbin/alsactl

usage() {
	echo "usage: $1 {start}"
}

case $1 in
	start)
		log_action_begin_msg "Restoring ALSA configuration"
		$ALSACTL restore
		log_action_end_msg $?
		;;

	stop)
		;;

	*)
		usage $0
		exit 1
		;;
esac
