#!/bin/sh

. /lib/lsb/init-functions

IFCONFIG=/sbin/ifconfig
UDHCPC=/sbin/udhcpc
HOSTNAME=medatom
IFACE=eth0
RETRIES=10
PIDFILE=/var/run/udhcpc.$IFACE.pid

usage()
{
	echo "usage: $1 {start|stop}"
}

case $1 in
	start)
		log_action_begin_msg "Bringing up network interface $IFACE"
		$IFCONFIG $IFACE up && \
			$UDHCPC -i $IFACE -h $HOSTNAME -t $RETRIES -p $PIDFILE
		log_action_end_msg $?
		;;

	stop)
		log_action_begin_msg "Taking down network interface $IFACE"
		if test -f "$PIDFILE"; then
			PID=`cat $PIDFILE`
			kill $PID && wait $PID
		fi
		$IFCONFIG $IFACE down
		log_action_end_msg $?
		;;

	*)
		usage $0
		exit 1
		;;
esac
