#!/bin/sh

. /lib/lsb/init-functions

PANGO_QUERYMODULES=/usr/bin/pango-querymodules
PANGO_MODULES=/etc/pango/pango.modules

usage() {
	echo "usage: $0 {start|stop}"
}

[ -x $PANGO_QUERYMODULES ] || exit 0

case $1 in
	start)
		log_action_begin_msg "Creating pango modules cache"
		$PANGO_QUERYMODULES > $PANGO_MODULES
		log_action_end_msg $?
		;;

	stop)
		;;

	*)
		usage $0
		exit 1
		;;
esac
