PACKAGE = medcom-wide-rootfs
VERSION = 5-wip

dirs = \
	/bin \
	/dev \
	/etc \
	/etc/X11 \
	/etc/X11/Xsession.d \
	/etc/X11/xorg.conf.d \
	/etc/adobe \
	/etc/fonts \
	/etc/fonts/conf.d \
	/etc/gtk-2.0 \
	/etc/iflinkd \
	/etc/iflinkd/hooks.d \
	/etc/modules-load.d \
	/etc/systemd \
	/etc/systemd/system \
	/etc/systemd/system/basic.target.wants \
	/etc/systemd/system/local-fs.target.wants \
	/etc/systemd/system/multi-user.target.wants \
	/etc/systemd/system/sockets.target.wants \
	/etc/pango \
	/etc/pam.d \
	/etc/remote-control.conf.d \
	/etc/tmpfiles.d \
	/etc/udev \
	/etc/udev/rules.d \
	/etc/xdg \
	/etc/xdg/awesome \
	/lib \
	/lib/firmware \
	/media \
	/media/disk \
	/persist \
	/proc \
	/root \
	/run \
	/sbin \
	/sys \
	/tmp \
	/usr \
	/usr/lib \
	/usr/lib/dhcpcd \
	/usr/lib/dhcpcd/dhcpcd-hooks \
	/usr/lib/gdk-pixbuf-2.0/2.10.0 \
	/var \
	/var/lib \
	/var/lock \
	/var/log

scripts = \
	/etc/X11/Xsession \
	/etc/iflinkd/hooks.d/00-lldpd \
	/etc/iflinkd/hooks.d/10-dhcpcd \
	/etc/xdg/awesome/xinitrc \
	/lib/systemd/gdk-pixbuf-loaders-cache \
	/lib/systemd/pango-modules-cache \
	/lib/systemd/update-mime-db \
	/usr/lib/dhcpcd/dhcpcd-hooks/90-ntp \
	/bin/reset-medcom \
	/bin/enable-lan

files = \
	/fastboot \
	/etc/X11/Xsession.d/00-persist \
	/etc/X11/Xsession.d/20-unexport-gpios \
	/etc/X11/Xsession.d/50-determine-startup \
	/etc/X11/Xsession.d/90-calibrate \
	/etc/X11/Xsession.d/99-start \
	/etc/X11/xorg.conf.d/05-evdev.conf \
	/etc/X11/xorg.conf.d/10-egalax.conf \
	/etc/X11/xorg.conf.d/80-server.conf \
	/etc/X11/xorg.conf.d/99-keyboard-de.conf \
	/etc/adobe/mms.cfg \
	/etc/asound.conf \
	/etc/fonts/conf.d/99-antialiasing.conf \
	/etc/fstab \
	/etc/group \
	/etc/gtk-2.0/gtkrc \
	/etc/host.conf \
	/etc/hosts \
	/etc/inittab \
	/etc/linphone.conf \
	/etc/localtime \
	/etc/modules-load.d/input.conf \
	/etc/nsswitch.conf \
	/etc/passwd \
	/etc/pam.conf \
	/etc/pam.d/common-account \
	/etc/pam.d/common-auth \
	/etc/pam.d/common-password \
	/etc/pam.d/common-session \
	/etc/pam.d/nodm \
	/etc/pam.d/other \
	/etc/profile \
	/etc/remote-control.conf.d/modem.conf \
	/etc/rsyslog.conf \
	/etc/services \
	/etc/shadow \
	/etc/sysctl.conf \
	/etc/systemd/system.conf \
	/etc/systemd/system/gdk-pixbuf.service \
	/etc/systemd/system/lldpd.service \
	/etc/systemd/system/lldpd.socket \
	/etc/systemd/system/nodm.service \
	/etc/systemd/system/openssh.service \
	/etc/systemd/system/pango.service \
	/etc/systemd/system/root.mount \
	/etc/systemd/system/tmp.mount \
	/etc/systemd/system/update-mime-db.service \
	/etc/systemd/system/var-lib.mount \
	/etc/systemd/system/var-log.mount \
	/etc/tmpfiles.d/dbus.conf \
	/etc/tmpfiles.d/lldpd.conf \
	/etc/tmpfiles.d/ntp.conf \
	/etc/tmpfiles.d/ssh.conf \
	/etc/tmpfiles.d/systemd.conf \
	/etc/udev/rules.d/70-persistent-net.rules \
	/etc/vconsole.conf \
	/lib/lsb/init-functions \
	/usr/share/alsa/ucm/tegrawm8903/hifi.conf \
	/usr/share/alsa/ucm/tegrawm8903/linein.conf \
	/usr/share/alsa/ucm/tegrawm8903/tegrawm8903.conf \
	/usr/share/alsa/ucm/tegrawm8903/voice-call.conf \
	/usr/share/alsa/ucm/tegrawm8903/voice-call-ip.conf

links = \
	/bin/sh \
	/etc/X11/xorg.conf.d/90-undefined.conf \
	/etc/X11/xorg.conf.d/99-calibration.conf \
	/etc/hostname \
	/etc/machine-id \
	/etc/motd \
	/etc/mtab \
	/etc/network \
	/etc/ntp.conf \
	/etc/remote-control.conf \
	/etc/resolv.conf \
	/etc/ssh/ssh_host_dsa_key \
	/etc/ssh/ssh_host_dsa_key.pub \
	/etc/ssh/ssh_host_ecdsa_key \
	/etc/ssh/ssh_host_ecdsa_key.pub \
	/etc/ssh/ssh_host_key \
	/etc/ssh/ssh_host_key.pub \
	/etc/ssh/ssh_host_rsa_key \
	/etc/ssh/ssh_host_rsa_key.pub \
	/etc/systemd/system/graphical.target.wants/gdk-pixbuf.service \
	/etc/systemd/system/graphical.target.wants/nodm.service \
	/etc/systemd/system/graphical.target.wants/pango.service \
	/etc/systemd/system/graphical.target.wants/update-mime-db.service \
	/etc/systemd/system/local-fs.target.wants/root.mount \
	/etc/systemd/system/local-fs.target.wants/tmp.mount \
	/etc/systemd/system/local-fs.target.wants/var-lib.mount \
	/etc/systemd/system/local-fs.target.wants/var-log.mount \
	/etc/systemd/system/multi-user.target.wants/network.target \
	/etc/systemd/system/multi-user.target.wants/serial-getty@ttyS0.service \
	/etc/systemd/system/multi-user.target.wants/openssh.service \
	/etc/systemd/system/sockets.target.wants/lldpd.socket \
	/etc/systemd/system/syslog.service \
	/etc/pango/pango.modules \
	/etc/proxy.conf \
	/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache \
	/var/run \
	/init \
	/sbin/halt \
	/sbin/init \
	/sbin/poweroff \
	/sbin/reboot \
	/sbin/runlevel \
	/sbin/shutdown

include include/config/auto.conf
include platforms/common.mk

quiet_cmd_edit = SED     $@
      cmd_edit = $(SED) 's|@VERSION@|$(VERSION)|' $< > $@

$(DESTDIR)/etc/os-release: $(obj)/src/etc/os-release.in $(obj)/Makefile
	$(call cmd,edit)

$(pkgtree)/.do-install: $(DESTDIR)/etc/os-release
