#!/bin/sh

SYSSESSIONDIR=/etc/X11/Xsession.d

SESSIONFILES=$(run-parts --list $SYSSESSIONDIR)
if test "x$SESSIONFILES" != "x"; then
	set +e
	for SESSIONFILE in $SESSIONFILES; do
		. $SESSIONFILE
	done
	set -e
fi

exit 0
